### ISSUE TITLE
resolve_genl_family hangs if kernel returns NLMSG_ERROR

### ISSUE THREAD

**Issue by joshtriplett** [jbaublitz/neli#87]
If the kernel doesn't have a generic netlink family (such as because the module implementing that family hasn't been loaded), it'll return an `NLMSG_ERROR` message. `resolve_genl_family` ignores that and proceeds to wait forever for an ack that will never arrive.

I *think* that `recv_nl` should be checking for an error.

**Comment by jbaublitz** [comment]
Hi @joshtriplett! Thanks for the issue. I'm actually taking a look at the `recv_nl` component of this for #31. I've been trying to take a phased approach to releases as I establish a new process for supporting older versions.

I think that the release `v0.5.0-r2` (which should be out very soon) should do what you're looking, but I'll double check just in case. Just be aware that the only way I was able to accomplish this was through some pretty significant changes to the API. You'll probably want to take a look at the branch `v0.5.0-dev` closely if you're interested in using the improved management of netlink protocol-level error handling.

**Comment by joshtriplett** [comment]
Major API changes aren't a problem; I'm just glad you may have a fix. Happy to test from git as soon as you have a potential fix posted.

**Comment by jbaublitz** [comment]
@joshtriplett Just wanted to let you know that as I was finishing this up, I realized I need to do a little bit of restructuring before the next release. The basic idea is splitting the message parsing code out into its own module so that all operations that interact with sockets (higher-level calls like `recv_nl`/message iteration and lower level calls like `recv`) can take advantage of certain functionality like error reporting. This has been a long standing issue that I've been hoping to resolve so I think this will make that transition cleaner and easier.

**Comment by joshtriplett** [comment]
@jbaublitz That sounds great, thank you!

**Comment by jbaublitz** [comment]
@joshtriplett I got your message on IRC and would be happy to chat on IRC when you're back on or here if I can be of help!

**Comment by joshtriplett** [comment]
@jbaublitz Just wanted to check back about the revised error handling, and find out a little bit more about what the API might look like. I'm interested in trying it out.

**Comment by jbaublitz** [comment]
Hi @joshtriplett, I'd recommend starting with building against the branch `v0.5.0-dev`. That's where the changes will be pushed soon and it's worth resolving the compilation errors when updating as those will still be there once the new error handling is added. Does that help?

**Comment by joshtriplett** [comment]
@jbaublitz I've looked at the `v0.5.0-dev` branch, and I plan to try that out as soon as the new error handling is available.

I'm currently trying to make use of the NBD netlink interface, and discovered that attempting to `resolve_genl_family` for nbd hangs if nbd is modular and not loaded, so I'm continuing to use the NBD ioctl interface for now.

**Comment by jbaublitz** [comment]
For anyone following along, @joshtriplett and I chatted and I'll be branching a simple fix for the 0.4.0 version. This bug will be resolved completely differently in 0.5.0, but because the refactoring in 0.5.0 is very involved, it will take a bit longer for the next release candidate.

**Comment by jbaublitz** [comment]
@joshtriplett Can you test the branch `0.4.x` and see what the behavior is there? If it doesn't resolve the problem (which I doubt it will to be honest), I can add some custom error parsing in the case of the `0.4.x` branch that will return an `NlError` so you at least have something to work with until v0.5.0 is released.

**Comment by joshtriplett** [comment]
@jbaublitz That fixed the primary issue, and `resolve_genl_family` now returns an error rather than hanging. Thanks!

It would certainly be nice for `recv_nl` to be able to handle getting a netlink error instead of the expected packet, and parse that error enough to provide the errno, in a type-safe way. But that can absolutely wait; the fix currently on the `0.4.x` branch is enough to get NBD working successfully.

**Comment by joshtriplett** [comment]
@jbaublitz Thank you so much for `neli`; it feels so *comfortable* to use.

**Comment by jbaublitz** [comment]
@joshtriplett I'm glad this partially resolved it! Depending on how much time I have, I may try to do some patchwork parsing in the `0.4.x` branch for you but I'm really trying to get rid of the 0.4 versions moving forward because of the huge API improvements from a maintenance standpoint in the v0.5.x versions. If I find that I don't have enough time to implement it on both branches, I'll release a `v0.4.4` for you to hold you over.

In any case, I'm really glad this has been helpful! If you have any feedback around how to make it better in the future, I always love hearing that too.

**Comment by joshtriplett** [comment]
@jbaublitz I'd be happy with the current state of the 0.4.x branch as a release; any better error handling could go in 0.5.x, since it'd likely need API changes anyway.

**Comment by joshtriplett** [comment]
Fixed in the 0.4.4 release. Thanks!
